export default {
  SIGNUP_USER_START: "SIGNUP_USER_START",
  SIGNUP_USER: "SIGNUP_USER",
  SIGNUP_USER_FAILED: "SIGNUP_USER_FAILED",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_FAILED: "LOGIN_USER_FAILED",
  LOGOUT_USER_START: "LOGIN_USER_START",
  LOGOUT_USER: "LOGOUT_USER"
};
