export default {
  GET_ALL_EVENTS: "GET_ALL_EVENTS",
  SET_ALL_EVENTS: "SET_ALL_EVENTS",
  GET_SELF_EVENTS: "GET_SELF_EVENTS",
  SET_SELF_EVENTS: "SET_SELF_EVENTS",
  ADD_EVENT_START: "ADD_EVENT_START",
  ADD_EVENT_FAILED: "ADD_EVENT_FAILED",
  GET_EVENT_ERROR: "GET_EVENT_ERROR",
  SET_EVENT_ERROR: "SET_EVENT_ERROR"
};
